id: P004259
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:05:28.030743
source_metadata:
  id: bdr:W1KG25914
  title: སྐྱིད་ཤོད་སྡེ་པའི་སྐོར།
  author: ''
  volumes:
    cb19c91edcc34fdaa31038fb82cf3476:
      image_group_id: I1KG25944
      title: ''
      volume_number: 1
      total_pages: 72
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
