id: I6C15604B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:06:45+00:00'
last_modified: '2022-06-07T21:29:03.347166+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25914
  title: སྐྱིད་ཤོད་སྡེ་པའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A59E:
      image_group_id: I1KG25944
      title: ''
      total_pages: 72
      order: 1
      base_file: A59E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
